import { MoreHoriz } from "@mui/icons-material";
import { IconButton } from "@mui/material";

export const columns = [
  {
    field: "type",
    headerName: "Type",
    width: 100,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    flex: 1,
    headerAlign: "center",
    align: "center",
    headerClassName: "header",
  },
  {
    field: "numVehicule",
    headerName: "Num de véhicule",
    width: 140,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    flex: 1.5,
    headerAlign: "center",
    align: "center",
    headerClassName: "header",
  },
  {
    field: "matricule",
    headerName: "Matricule",
    width: 100,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    flex: 1,
    headerAlign: "center",
    align: "center",
    headerClassName: "header",
  },
  {
    field: "marque",
    headerName: "Marque",
    width: 100,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    flex: 1,
    headerAlign: "center",
    align: "center",
    headerClassName: "header",
  },

  {
    field: "modele",
    headerName: "Modéle",
    width: 100,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    flex: 1,
    headerAlign: "center",
    align: "center",
    headerClassName: "header",
  },
  {
    field: "puissance",
    headerName: "Puissance",
    width: 100,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    flex: 1,
    headerAlign: "center",
    align: "center",
    headerClassName: "header",
  },
  {
    field: "nbCheveaux",
    headerName: "Nb de cheveaux",
    width: 140,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    flex: 1.5,
    headerAlign: "center",
    align: "center",
    headerClassName: "header",
  },
  {
    field: "couleur",
    headerName: "Couleur",
    width: 100,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    flex: 1,
    headerAlign: "center",
    align: "center",
    headerClassName: "header",
  },
  {
    field: "annee",
    headerName: "Année",
    width: 100,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    flex: 1,
    headerAlign: "center",
    align: "center",
    headerClassName: "header",
  },
  {
    field: "action",
    headerName: "Action",
    width: 100,
    editable: false,
    sortable: false,
    disableColumnMenu: true,
    flex: 1,
    headerAlign: "center",
    align: "center",
    headerClassName: "header",
    renderCell: () => {
      return (
        <IconButton>
          <MoreHoriz sx={{ color: "#075d8f" }} />
        </IconButton>
      );
    },
  },
];

export const rows = [
  {
    id: 1,
    type: "Voiture",
    numVehicule: "024579654",
    matricule: "024579654",
    marque: "Audi",
    modele: "Q2 35 TFSI",
    puissance: "2000",
    nbCheveaux: "5",
    couleur: "gris",
    annee: "2019",
  },
  {
    id: 2,
    type: "Voiture",
    numVehicule: "457812578",
    matricule: "457812578",
    marque: "Audi",
    modele: "Q2 35 TFSI",
    puissance: "5000",
    nbCheveaux: "8",
    couleur: "blue",
    annee: "2021",
  },
  {
    id: 3,
    type: "Bicyclette",
    numVehicule: "........",
    matricule: "........",
    marque: "cavendish",
    modele: "9867SS",
    puissance: "........",
    nbCheveaux: "........",
    couleur: "blanc",
    annee: "2020",
  },
  {
    id: 4,
    type: "Voiture",
    numVehicule: "024579654",
    matricule: "024579654",
    marque: "Audi",
    modele: "Q2 35 TFSI",
    puissance: "2000",
    nbCheveaux: "5",
    couleur: "gris",
    annee: "2019",
  },
  {
    id: 5,
    type: "Voiture",
    numVehicule: "457812578",
    matricule: "457812578",
    marque: "Audi",
    modele: "Q2 35 TFSI",
    puissance: "5000",
    nbCheveaux: "8",
    couleur: "blue",
    annee: "2021",
  },
  {
    id: 6,
    type: "Bicyclette",
    numVehicule: "........",
    matricule: "........",
    marque: "cavendish",
    modele: "9867SS",
    puissance: "........",
    nbCheveaux: "........",
    couleur: "blanc",
    annee: "2020",
  },
  {
    id: 7,
    type: "Bicyclette",
    numVehicule: "........",
    matricule: "........",
    marque: "cavendish",
    modele: "9867SS",
    puissance: "........",
    nbCheveaux: "........",
    couleur: "blanc",
    annee: "2020",
  },
];